export function getAuthErrorMessage(code: any): string {
  const map: Record<string, string> = {
    anonymous_provider_disabled: "Đăng nhập ẩn danh đang bị tắt.",
    bad_code_verifier: "Lỗi xác thực đăng nhập. Vui lòng thử lại.",
    bad_json: "Dữ liệu gửi lên không hợp lệ.",
    bad_jwt: "Phiên đăng nhập không hợp lệ.",
    bad_oauth_callback: "Đăng nhập bằng mạng xã hội thất bại.",
    bad_oauth_state: "Trạng thái đăng nhập OAuth không hợp lệ.",
    captcha_failed: "Xác thực CAPTCHA thất bại.",
    conflict: "Có xung đột dữ liệu. Vui lòng thử lại sau.",
    email_address_invalid: "Email không hợp lệ.",
    email_address_not_authorized: "Email này chưa được phép nhận thư xác thực.",
    email_conflict_identity_not_deletable:
      "Email này đang được dùng cho tài khoản khác.",
    email_exists: "Email đã được đăng ký.",
    email_not_confirmed: "Email chưa được xác thực.",
    email_provider_disabled: "Đăng ký bằng email đang bị tắt.",
    flow_state_expired: "Phiên đăng nhập đã hết hạn.",
    flow_state_not_found: "Phiên đăng nhập không tồn tại.",
    hook_payload_invalid_content_type: "Dữ liệu hook không hợp lệ.",
    hook_payload_over_size_limit: "Dữ liệu hook quá lớn.",
    hook_timeout: "Xử lý xác thực bị quá thời gian.",
    hook_timeout_after_retry: "Xác thực thất bại sau nhiều lần thử.",
    identity_already_exists: "Tài khoản đã được liên kết.",
    identity_not_found: "Không tìm thấy thông tin xác thực.",
    insufficient_aal: "Cần xác thực bổ sung (MFA).",
    invalid_credentials: "Email hoặc mật khẩu không đúng.",
    invite_not_found: "Lời mời không hợp lệ hoặc đã hết hạn.",
    manual_linking_disabled: "Không cho phép liên kết tài khoản thủ công.",
    mfa_challenge_expired: "Mã xác thực đã hết hạn.",
    mfa_factor_name_conflict: "Tên phương thức xác thực bị trùng.",
    mfa_factor_not_found: "Không tìm thấy phương thức xác thực.",
    mfa_ip_address_mismatch: "Địa chỉ IP xác thực không khớp.",
    mfa_phone_enroll_not_enabled: "Xác thực bằng số điện thoại bị tắt.",
    mfa_phone_verify_not_enabled: "Không thể xác thực bằng điện thoại.",
    mfa_totp_enroll_not_enabled: "Xác thực TOTP bị tắt.",
    mfa_totp_verify_not_enabled: "Không thể xác thực TOTP.",
    mfa_verification_failed: "Mã xác thực không đúng.",
    mfa_verification_rejected: "Xác thực bị từ chối.",
    mfa_verified_factor_exists: "Phương thức xác thực đã tồn tại.",
    mfa_web_authn_enroll_not_enabled: "WebAuthn MFA bị tắt.",
    mfa_web_authn_verify_not_enabled: "Không thể xác thực WebAuthn.",
    no_authorization: "Thiếu thông tin xác thực.",
    not_admin: "Bạn không có quyền thực hiện thao tác này.",
    oauth_provider_not_supported: "Nhà cung cấp đăng nhập chưa được hỗ trợ.",
    otp_disabled: "Đăng nhập bằng OTP đang bị tắt.",
    otp_expired: "Mã OTP đã hết hạn.",
    over_email_send_rate_limit: "Gửi email quá nhiều lần. Vui lòng chờ.",
    over_request_rate_limit: "Thao tác quá nhanh. Vui lòng thử lại sau.",
    over_sms_send_rate_limit: "Gửi SMS quá nhiều lần.",
    phone_exists: "Số điện thoại đã được sử dụng.",
    phone_not_confirmed: "Số điện thoại chưa được xác thực.",
    phone_provider_disabled: "Đăng ký bằng số điện thoại bị tắt.",
    provider_disabled: "Phương thức đăng nhập này đang bị tắt.",
    provider_email_needs_verification: "Cần xác thực email từ nhà cung cấp.",
    reauthentication_needed: "Cần xác thực lại để tiếp tục.",
    reauthentication_not_valid: "Mã xác thực lại không đúng.",
    refresh_token_already_used: "Phiên đăng nhập đã hết hiệu lực.",
    refresh_token_not_found: "Không tìm thấy phiên đăng nhập.",
    request_timeout: "Yêu cầu xử lý quá lâu.",
    same_password: "Mật khẩu mới phải khác mật khẩu cũ.",
    saml_assertion_no_email: "Không nhận được email từ SSO.",
    saml_assertion_no_user_id: "Thiếu thông tin người dùng từ SSO.",
    saml_entity_id_mismatch: "Cấu hình SSO không khớp.",
    saml_idp_already_exists: "Nhà cung cấp SSO đã tồn tại.",
    saml_idp_not_found: "Không tìm thấy nhà cung cấp SSO.",
    saml_metadata_fetch_failed: "Không thể tải metadata SSO.",
    saml_provider_disabled: "SSO doanh nghiệp đang bị tắt.",
    saml_relay_state_expired: "Phiên SSO đã hết hạn.",
    saml_relay_state_not_found: "Phiên SSO không tồn tại.",
    session_expired: "Phiên đăng nhập đã hết hạn.",
    session_not_found: "Phiên đăng nhập không tồn tại.",
    signup_disabled: "Chức năng đăng ký đang bị tắt.",
    single_identity_not_deletable:
      "Không thể xoá phương thức đăng nhập duy nhất.",
    sms_send_failed: "Gửi SMS thất bại.",
    sso_domain_already_exists: "Tên miền SSO đã tồn tại.",
    sso_provider_not_found: "Không tìm thấy nhà cung cấp SSO.",
    too_many_enrolled_mfa_factors: "Đã vượt quá số MFA cho phép.",
    unexpected_audience: "Đối tượng xác thực không hợp lệ.",
    unexpected_failure: "Có lỗi hệ thống xảy ra.",
    user_already_exists: "Tài khoản đã tồn tại.",
    user_banned: "Tài khoản đang bị khóa.",
    user_not_found: "Không tìm thấy người dùng.",
    user_sso_managed: "Tài khoản SSO không thể chỉnh sửa.",
    validation_failed: "Dữ liệu không hợp lệ.",
    weak_password: "Mật khẩu quá yếu.",
  };

  return map[code ?? ""] ?? "Đã xảy ra lỗi. Hãy thử lại.";
}
